### ISSUE TITLE
Issue upgrading to v5 in Lerna Monorepo

### ISSUE THREAD

**Issue by leerob** [manovotny/eslint-config-get-off-my-lawn#120]
When trying to update our [Lerna monorepo](https://github.com/Hy-Vee/lerna-yarn-workspaces-monorepo), I hit this error.
```
yarn run v1.16.0
$ yarn lint:js && yarn lint:styles
$ eslint . --ext .js --ignore-pattern lib --ignore-pattern node_modules
TypeError: Cannot read config file: /Users/leerobinson/Developer/lerna-yarn-workspaces-monorepo/node_modules/eslint-config-get-off-my-lawn/index.js
Error: Invalid Version: ^16.8.6
Referenced from: /Users/leerobinson/Developer/lerna-yarn-workspaces-monorepo/.eslintrc.js
    at new SemVer (/Users/leerobinson/Developer/lerna-yarn-workspaces-monorepo/node_modules/semver/semver.js:332:11)
    at compare (/Users/leerobinson/Developer/lerna-yarn-workspaces-monorepo/node_modules/semver/semver.js:647:10)
    at Function.gte (/Users/leerobinson/Developer/lerna-yarn-workspaces-monorepo/node_modules/semver/semver.js:703:10)
    at Object.<anonymous> (/Users/leerobinson/Developer/lerna-yarn-workspaces-monorepo/node_modules/eslint-config-get-off-my-lawn/index.js:73:16)
    at Module._compile (/Users/leerobinson/Developer/lerna-yarn-workspaces-monorepo/node_modules/v8-compile-cache/v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
```

I can't pinpoint what this error is telling me. Can I not use carets in versions?

Really all I changed was this:

```json
"eslint": "^6.2.2",
"eslint-config-get-off-my-lawn": "^5.0.0",
```

**Comment by leerob** [comment]
Yep, that was it. Removing the caret fixes things.

**Comment by leerob** [comment]
https://github.com/Hy-Vee/lerna-yarn-workspaces-monorepo/pull/6

**Comment by manovotny** [comment]
Hrm, that doesn’t seem right. 🤔

I’ll try and reproduce tonight.

**Comment by manovotny** [comment]
@leerob when does this throw? Updating using yarn? Running `yarn dev`?

**Comment by leerob** [comment]
Running `yarn lint`.
