### ISSUE TITLE
error - ESLint: Cannot read config fileError: Invalid Version: ^4.6.3 Referenced from

### ISSUE THREAD

**Issue by talatkuyuk** [manovotny/eslint-config-get-off-my-lawn#197]
When I upgrade to typescript 4.6.3, I receive the error message in my nextjs application..

`error - ESLint: Cannot read config file: /Users/talatkuyuk/MyCodeRepo/nextprojects/amazon-ht-web/node_modules/eslint-config-get-off-my-lawn/index.js Error: Invalid Version: ^4.6.3 Referenced from: /Users/talatkuyuk/MyCodeRepo/nextprojects/amazon-ht-web/.eslintrc.js
`

I use `"eslint-config-get-off-my-lawn": "^7.0.4",`

What should I have to do?

`
Oops! Something went wrong! :(

ESLint: 8.13.0

TypeError: Cannot read config file: /Users/talatkuyuk/MyCodeRepo/nextprojects/amazon-ht-web/node_modules/eslint-config-get-off-my-lawn/index.js
Error: Invalid Version: ^4.6.3
Referenced from: /Users/talatkuyuk/MyCodeRepo/nextprojects/amazon-ht-web/.eslintrc.js
    at new SemVer (/Users/talatkuyuk/MyCodeRepo/nextprojects/amazon-ht-web/node_modules/semver/classes/semver.js:38:13)
    at compare (/Users/talatkuyuk/MyCodeRepo/nextprojects/amazon-ht-web/node_modules/semver/functions/compare.js:3:3)
    at Object.lt (/Users/talatkuyuk/MyCodeRepo/nextprojects/amazon-ht-web/node_modules/semver/functions/lt.js:2:29)
    at Object.<anonymous> (/Users/talatkuyuk/MyCodeRepo/nextprojects/amazon-ht-web/node_modules/eslint-config-get-off-my-lawn/src/typescript.js:307:26)
    at Module._compile (/Users/talatkuyuk/MyCodeRepo/nextprojects/amazon-ht-web/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1147:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (/Users/talatkuyuk/MyCodeRepo/nextprojects/amazon-ht-web/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)`

**Comment by manovotny** [comment]
Thanks for filing an issue! This should be fixed in [v7.0.5](https://github.com/manovotny/eslint-config-get-off-my-lawn/releases/tag/v7.0.5).
